### PR TITLE
feat: add copyright notice to tp

### PR DESCRIPTION
**Pull request by ArchiFleKs**

### CODE REVIEW

**Comment by ArchiFleKs** [comment]
@rguichard can we merge this ?

**Comment by rguichard** [comment]
I'd like to make some changes. "copyright" should be a module we can use for TP and courses.

We should rewrite "intro-particule" to : 

- talk about us a little bit more
- remove the copyright

Module "copyright" would be load just after the introduction for the courses

**Comment by ArchiFleKs** [comment]
@rguichard it should work like you wanted to. You can modify the `intro-particule.$LANG.md` to add a more detail description.

**Comment by rguichard** [comment]
@mergifyio refresh

**Pull request merged**
